***Task 1***

In [1]:
student = {
    "name": "Anuj",
    "course": "AIML",
    "skills": ["Python", "Pandas", "NumPy"],
    "city": "Mahendragarh"
}
def create_profile(profile: dict) -> str:

    skills = ", ".join(profile["skills"])

    return (
        f"Name: {profile['name']}\n"
        f"Course: {profile['course']}\n"
        f"Skills: {skills}\n"
        f"City: {profile['city']}"
    )
print(create_profile(student))

Name: Anuj
Course: AIML
Skills: Python, Pandas, NumPy
City: Mahendragarh


***Task 2***

In [4]:
import json
with open("profile.json", "r") as file:

    data = json.load(file)
skills = [
    skill.upper()
    for skill in data["skills"]
]
print(f"Name : {data['name']}")
print(f"Role : {data['role']}")
print(f"Skills : {', '.join(skills)}")

Name : Anuj
Role : AIML Intern
Skills : PYTHON, SQL, PANDAS


***Task 3***

In [5]:
class Learner:
    def __init__(self, name, course):

        self.name = name
        self.course = course
    def show_details(self):

        return (
            f"{self.name} is learning "
            f"{self.course}"
        )
student1 = Learner(
    "Anuj",
    "Python"
)
print(student1.show_details())

Anuj is learning Python


***Task 4***

In [6]:
import pandas as pd
data = {

    "name": [
        "Anuj","Rahul","Priya","Amit","Neha"
    ],

    "city": [
        "Delhi","Mumbai","Delhi","Pune","Mumbai"
    ],

    "score": [
        92,70,85,60,95
    ]
}
df = pd.DataFrame(data)
selected_columns = df[
    ["name", "score"]
]
print("\nSelected Columns:")
print(selected_columns)
filtered_data = df[
    (df["score"] > 80)
    &
    (df["city"] == "Delhi")
]
print("\nFiltered Rows:")
print(filtered_data)


Selected Columns:
    name  score
0   Anuj     92
1  Rahul     70
2  Priya     85
3   Amit     60
4   Neha     95

Filtered Rows:
    name   city  score
0   Anuj  Delhi     92
2  Priya  Delhi     85


***Task 5***

In [1]:
import pandas as pd
data = {

    "name": [
        "Anuj","Rahul","Priya","Amit"
    ],

    "city": [
        "Delhi","Mumbai","Pune","Delhi"
    ],

    "score": [
        92,
        70,
        85,
        60
    ]
}
df = pd.DataFrame(data)
print("\nUsing .loc")

print(
    df.loc[
        1:2,
        ["name", "score"]
    ]
)
print("\nUsing .iloc")

print(
    df.iloc[
        1:3,
        0:2
    ]
)


Using .loc
    name  score
1  Rahul     70
2  Priya     85

Using .iloc
    name    city
1  Rahul  Mumbai
2  Priya    Pune


***Task 6***

In [3]:
import numpy as np
data = {

    "name": [
        "Anuj",
        "Rahul",
        "Priya",
        "Amit"
    ],

    "score": [
        92,
        np.nan,
        85,
        60
    ],

    "city": [
        "Delhi",
        "Mumbai",
        np.nan,
        "Pune"
    ]
}
df = pd.DataFrame(data)
print("\nMissing Values:")
print(df.isnull().sum())
drop_data = df.dropna()

print("\nAfter dropna():")
print(drop_data)
fill_data = df.fillna({

    "score": 0,
    "city": "Unknown"
})

print("\nAfter fillna():")
print(fill_data)


Missing Values:
name     0
score    1
city     1
dtype: int64

After dropna():
   name  score   city
0  Anuj   92.0  Delhi
3  Amit   60.0   Pune

After fillna():
    name  score     city
0   Anuj   92.0    Delhi
1  Rahul    0.0   Mumbai
2  Priya   85.0  Unknown
3   Amit   60.0     Pune


***Task 7***

In [4]:
data = {

    "name": [
        "Anuj",
        "Rahul",
        "Priya",
        "Amit",
        "Neha"
    ],

    "city": [
        "Delhi",
        "Mumbai",
        "Delhi",
        "Pune",
        "Mumbai"
    ],

    "score": [
        92,
        70,
        85,
        60,
        95
    ]
}
df = pd.DataFrame(data)
print("\nDescribe Output:")
print(df["score"].describe())
print("\nCity Counts:")
print(df["city"].value_counts())
print("\nObservation:")
print("Highest score is 95")

print(
    "Delhi and Mumbai each appear 2 times"
)


Describe Output:
count     5.000000
mean     80.400000
std      14.943226
min      60.000000
25%      70.000000
50%      85.000000
75%      92.000000
max      95.000000
Name: score, dtype: float64

City Counts:
city
Delhi     2
Mumbai    2
Pune      1
Name: count, dtype: int64

Observation:
Highest score is 95
Delhi and Mumbai each appear 2 times


***Task 8***

In [5]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.arange(1, 11)
array3 = np.zeros((2, 3))
array4 = np.linspace(0, 1, 5)
print("\nArray 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nArray 3:")
print(array3)
print("\nArray 4:")
print(array4)
print("\nArray Information:")
print("Shape:", array3.shape)
print("Data Type:", array1.dtype)
print("Dimensions:", array3.ndim)
print("\nNegative Index:")
print(array1[-1])
print("\nSlice:")
print(array2[2:7])


Array 1:
[1 2 3 4 5]

Array 2:
[ 1  2  3  4  5  6  7  8  9 10]

Array 3:
[[0. 0. 0.]
 [0. 0. 0.]]

Array 4:
[0.   0.25 0.5  0.75 1.  ]

Array Information:
Shape: (2, 3)
Data Type: int64
Dimensions: 2

Negative Index:
5

Slice:
[3 4 5 6 7]


***Task 9***

In [6]:
array = np.array([10, 20, 30, 40, 50])
mask = array > 25
filtered_values = array[mask]
print("Original Array:")
print(array)
print("\nBoolean Mask:")
print(mask)
print("\nFiltered Values:")
print(filtered_values)
scaled_array = array + 5
print("\nBroadcasted Array:")
print(scaled_array)
def cosine_similarity(vec1, vec2):
    dot_product = np.dot(vec1, vec2)
    norm_vec1 = np.linalg.norm(vec1)
    norm_vec2 = np.linalg.norm(vec2)
    similarity = (
        dot_product /
        (norm_vec1 * norm_vec2)
    )
    return similarity
v1 = np.array([1, 2, 3])
v2 = np.array([1, 2, 3])
v3 = np.array([1, 0, 0])
v4 = np.array([0, 1, 0])
print("\nCosine Similarity 1:")
print(cosine_similarity(v1, v2))

print("\nCosine Similarity 2:")
print(cosine_similarity(v3, v4))

Original Array:
[10 20 30 40 50]

Boolean Mask:
[False False  True  True  True]

Filtered Values:
[30 40 50]

Broadcasted Array:
[15 25 35 45 55]

Cosine Similarity 1:
1.0

Cosine Similarity 2:
0.0
